language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - cmake
      - cmake-data
      - libboost-dev

compiler:
  - g++

install:
  - git clone https://github.com/google/googletest googletest
  - mkdir -p gtest
  - cd gtest
  - export GTEST_LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$(pwd) ../googletest
  - make && make install
  - cd -
  - export CMAKE_OPTIONS="$CMAKE_OPTIONS -DGTEST_ROOT=${GTEST_LIBRARY_PATH}"

script:
  - ${CXX} --version
  - cmake ${CMAKE_OPTIONS} .
  - make VERBOSE=1 result-test-exe
  - ./result-test-exe
