sudo: false

language: c++

dist: trusty

matrix:
  include:
    - os: linux
      compiler: g++
      env: COMPILER_VERSION=4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libboost-dev
    - os: osx
      compiler: clang++
      addons:
        apt:
          packages:
            - cmake
            - libboost-dev
    - os: linux
      compiler: g++
      env: COMPILER_VERSION=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libboost-dev
    - os: linux
      compiler: g++
      env: COMPILER_VERSION=6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libboost-dev

before_install:
  - if [ "${COMPILER_VERSION}" == "4" ]; then export CXX=g++; fi
  - if [ "${COMPILER_VERSION}" == "5" ]; then export CXX=g++-5; fi
  - if [ "${COMPILER_VERSION}" == "6" ]; then export CXX=g++-6; fi

install:
  - git clone https://github.com/google/googletest googletest
  - mkdir -p gtest
  - cd gtest
  - export GTEST_LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$(pwd) ../googletest
  - make && make install
  - cd -
  - export CMAKE_OPTIONS="$CMAKE_OPTIONS -DGTEST_ROOT=${GTEST_LIBRARY_PATH}"

script:
  - ${CXX} --version
  - cmake ${CMAKE_OPTIONS} .
  - make VERBOSE=1 result-test-exe
  - ./result-test-exe
